StaffPortal/Entities/Salary.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StaffPortal.Entities
{
    public class Salary
    {
        public int Id { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public UserProfile UserProfile { get; set; }
        public int UserProfileId { get; set; }
        public string CreatedBy { get; set; }
        private DateTime? dateCreated = null;
        public DateTime DateCreated
        {
            get
            {
                return dateCreated ?? DateTime.Now;
            }

            set { dateCreated = value; }

        }
        public double YearAllow { get; set; }
        public double YearDeduction { get; set; }
        public double YearPay { get; set; }
        public Leave Leave { get; set; }
        public int LeaveId { get; set; }                                    //public double TransportPercent_ { get; set; }
                                                                                   //public double Transport  { get; set; }
                                                                                   //public double Allowance { get; set; }
                                                                                   // public double  { get; set; }


    }
}

StaffPortal/Controllers/SalaryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StaffPortal.Models;
using StaffPortal.Interface;
using StaffPortal.Entities;
using StaffPortal.Enums;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using StaffPortal.Data;
using Microsoft.EntityFrameworkCore;

namespace StaffPortal.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class SalaryController : BaseController

    {
        private ISalary _salary;
        private StaffPortalDataContext _context;
        private IUserProfile _userProfile;

        private readonly UserManager<ApplicationUser> _userManager;
        public SalaryController(ISalary salary, IUserProfile userProfile, StaffPortalDataContext context, UserManager<ApplicationUser> userManager)
        {
            _salary = salary;
            _context = context;
            _userProfile = userProfile;
            _userManager = userManager;
        }

        //public async Task<IActionResult> Index()
        //{

        //    var model = await _salary.GetAll();

        //    if (model != null)
        //        return View(model);
        //    return View();
        //}
        //public async Task<IActionResult> test(string searchString)
        //{
        //    var salary = from m in _context.Salaries
        //                 select m;

        //    if (!String.IsNullOrEmpty(searchString))
        //    {
        //        //salary = salary.Where(s => s.Month.Contains(searchString) || s.Year.Contains(searchString) || s.DateCreated.ToString().Contains(searchString) || s.CreatedBy.Contains(searchString));
        //        salary = salary.Where(s => s.Month.Contains(searchString) );

        //    }

        //    return View(await salary.ToListAsync());
        //}


        //public async Task<IActionResult> test(string salaryMonth, string salaryYear, string searchString)
        //{

        //    IQueryable<string> monthQuery = from m in _context.Salaries
        //                                    orderby m.Month
        //                                    select m.Month;

        //    IQueryable<string> yearQuery = from m in _context.Salaries
        //                                    orderby m.Year
        //                                    select m.Year;

        //    var salaries = from m in _context.Salaries
        //                 select m;

        //    if (!String.IsNullOrEmpty(searchString))
        //    {
        //        salaries = salaries.Where(s => s.Month.Contains(searchString) || s.Year.Contains(searchString) || s.DateCreated.ToString().Contains(searchString) || s.CreatedBy.Contains(searchString));
        //    }

        //    if (!string.IsNullOrEmpty(salaryMonth))
        //    {
        //        salaries = salaries.Where(x => x.Month == salaryMonth);
        //    }

        //    if (!string.IsNullOrEmpty(salaryYear))
        //    {
        //        salaries = salaries.Where(x => x.Year == salaryYear);
        //    }

        //    var salaryMonthVM = new SalaryMonthViewModel
        //    {
        //        Months = new SelectList(await monthQuery.Distinct().ToListAsync()),
        //        Years = new SelectList(await yearQuery.Distinct().ToListAsync()),
        //        Sals = await salaries.ToListAsync()
        //    };

        //    return View(salaryMonthVM);



        //}
        
        [HttpGet]
        public async Task<IActionResult> UserYear()
        {

            var user = _userManager.GetUserName(User);
            var x = await _userManager.FindByNameAsync(user);

            var sal = _userProfile.GetIdByEmail(x.Email);
            if (sal != 0)
            {
                var usersal = await _salary.GetUserYear(sal);
                if (usersal != null)
                {
                    return View(usersal);
                }
            }



            return RedirectToAction("UserError", "UserProfile");

        }

        public async Task<IActionResult> UserMonthlyReport()
        {
            var user = _userManager.GetUserName(User);
            var x = await _userManager.FindByNameAsync(user);

            var sal = _userProfile.GetIdByEmail(x.Email);
            if (sal != 0)
            {
                var usersal = await _salary.GetAllMonthlyReport(sal);
                if (usersal != null)
                {
                    return View(usersal);
                }
            }
            return RedirectToAction("UserError");
        }


        public async Task<IActionResult> Year()
        {
            var model = await _salary.GetYear();

            if (model != null)
            {

                return View(model);
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> YearlyReport(int id)
        {
           
           
            var sal = await _salary.GetById(id);
            var userp = await _userProfile.GetById(sal.UserProfileId);
            var x = await _userManager.FindByEmailAsync(userp.Email);
            var model = await _salary.GetById(sal);

            var salaryYearVM = new SalaryYearViewModel
            {
                //Months = new SelectList(await monthQuery.Distinct().ToListAsync()),
                //Years = new SelectList(await yearQuery.Distinct().ToListAsync()),
                //Gradenames = new SelectList(await gradeQuery.Distinct().ToListAsync()),
                FullName = x.FullName,
                Appuser = await _context.Users.Where(a => a.Email == userp.Email).ToListAsync(),
                Grades = await _context.Grades.Where(a => a.Id == userp.GradeId).ToListAsync(),
                Sals = await _context.Salaries.Include(u => u.UserProfile).Where(a => a.Year == sal.Year).Where(a => a.UserProfileId == sal.UserProfileId).ToListAsync()


                //Sals = await PaginatedList<Salary>.CreateAsync(salaries.AsNoTracking(), pageNumber ?? 1, pageSize)
            };

            return View(salaryYearVM);



            //if (model != null)
            //{

            //    return View(model);
            //}
            //return View();
        }

        [HttpGet]
        public async Task<IActionResult> UserYearlyReport(int id)
        {


            var sal = await _salary.GetById(id);
            var userp = await _userProfile.GetById(sal.UserProfileId);
            var x = await _userManager.FindByEmailAsync(userp.Email);
          //  var model = await _salary.GetYearReport(sal);

            var salaryYearVM = new SalaryYearViewModel
            {
               
                FullName = x.FullName,
                Appuser = await _context.Users.Where(a => a.Email == userp.Email).ToListAsync(),
                Grades = await _context.Grades.Where(a => a.Id == userp.GradeId).ToListAsync(),
                Sals = await _context.Salaries.Include(u => u.UserProfile).Where(a => a.Year == sal.Year).Where(a => a.UserProfileId == sal.UserProfileId).ToListAsync()
            };

            return View(salaryYearVM);



        }


        public async Task<IActionResult> Index(string salaryMonth, string salaryYear, string searchString, string Sorting_Order, string currentFilter, int? pageNumber)
        {
            ViewBag.CurrentSort = Sorting_Order;
            ViewBag.SortingMonth = String.IsNullOrEmpty(Sorting_Order) ? "Month_Desc" : "";
            ViewBag.SortingYear = Sorting_Order == "Year" ? "Year_Desc" : "Year";
            ViewBag.SortingDate = Sorting_Order == "Date_created" ? "Date_Desc" : "Date_created";
            ViewBag.SortingCreate = Sorting_Order == "CreatedBy" ? "CreatedBy_Desc" : "CreatedBy";
            ViewBag.SortingId = Sorting_Order == "ID" ? "ID_Desc" : "ID";
            ViewBag.Sortingfirst = Sorting_Order == "UserProfile" ? "UserProfile_Desc" : "UserProfile";
            ViewBag.Sortinglast = Sorting_Order == "UserProfilelast" ? "UserProfile_Desclast" : "UserProfilelast";
            ViewBag.Sortingemail = Sorting_Order == "UserProfileemail" ? "UserProfile_Descemail" : "UserProfileemail";

            IQueryable<string> monthQuery = from m in _context.Salaries
                                            orderby m.Month
                                            select m.Month;

            IQueryable<string> yearQuery = from m in _context.Salaries
                                           orderby m.Year
                                           select m.Year;
            IQueryable<string> gradeQuery = from m in _context.Salaries
                                           orderby m.UserProfile.GradeName
                                           select m.UserProfile.GradeName;

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            var salaries = from m in _context.Salaries
                           select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                salaries = salaries.Where(s => s.Month.Contains(searchString) || s.Year.Contains(searchString) || s.DateCreated.ToString().Contains(searchString) || s.CreatedBy.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(salaryMonth))
            {
                salaries = salaries.Where(x => x.Month == salaryMonth);
            }

            if (!string.IsNullOrEmpty(salaryYear))
            {
                salaries = salaries.Where(x => x.Year == salaryYear);
            }
            //IQueryable salariesList = new List<Salary>();
            //IQueryable<T> salariesList;
            switch (Sorting_Order)
            {
                case "Month_Asc":
                    //students = students.OrderByDescending(stu => stu.FirstName);

StaffPortal/Views/Salary/Empty .cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

StaffPortal/Views/Salary/Index.cshtml
@using StaffPortal.Entities

@model StaffPortal.Models.SalaryMonthViewModel
@*    @model IEnumerable<StaffPortal.Entities.Salary>*@
@{
    ViewBag.Title = "Index";
}
<!-- ============================================================== -->

<div class="row bg-title">
    <div class="col-lg-12">
        <h4 class="page-title">Salary</h4>
        <ol class="breadcrumb">
            <li><a href="#">Dashboard</a></li>
            <li class="active">Salary</li>
        </ol>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-sm-12">

        <div class="white-box">

            <a asp-controller="Salary" asp-action="Create" class="btn float-right hidden-sm-down btn-success"><i class="mdi mdi-plus-circle"></i>New Salary</a>
            <div style="font-family:Arial">

                <form asp-controller="Salary" asp-action="Index" method="get">
                    <p>
                        Month: <select asp-for="SalaryMonth" asp-items="Model.Months">
                            <option value="">All</option>
                        </select>

                        Year: <select asp-for="SalaryYear" asp-items="Model.Years">
                            <option value="">All</option>
                        </select>
                        GradeName: <select asp-for="SalaryGradeName" asp-items="Model.Gradenames">
                            <option value="">All</option>
                        </select>

                        <br />
                        Word index: <input type="text" name="SearchString">
                        <input type="submit" value="Filter" />
                    </p>
                </form>

                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.ActionLink("Id", "Index", new { Sorting_Order = ViewBag.SortingId })
                                </th>
                                <th>
                                    @Html.ActionLink("First Name", "Index", new { Sorting_Order = ViewBag.Sortingfirst })
                                </th>
                                <th>
                                    @Html.ActionLink("LastName", "Index", new { Sorting_Order = ViewBag.Sortinglast })
                                </th>
                                <th>
                                    @Html.ActionLink("Email", "Index", new { Sorting_Order = ViewBag.Sortingemail })
                                </th>
                                <th>
                                    @Html.ActionLink("Grade", "Index", new { Sorting_Order = ViewBag.SortingMonth })
                                </th>
                                <th>
                                    @Html.ActionLink("Month", "Index", new { Sorting_Order = ViewBag.SortingMonth })
                                </th>
                                <th>
                                    @Html.ActionLink("Year", "Index", new { Sorting_Order = ViewBag.SortingYear })
                                </th>
                                <th>Basic Salary</th>
                                <th>Total Allowance</th>
                                <th>Total Deduction</th>
                                <th>Net Pay</th>
                                <th>
                                    @Html.ActionLink("CreatedBy", "Index", new { Sorting_Order = ViewBag.SortingCreate })
                                </th>
                                <th>
                                    @Html.ActionLink("DateCreated", "Index", new { Sorting_Order = ViewBag.SortingDate })
                                </th>

                            </tr>

                        </thead>
                        <tbody>

                            @foreach (var Salary in Model.Sals)
                            {
                            <tr>
                                <td>@Salary.Id</td>

                                <td>@Salary.UserProfile.FirstName   </td>
                                <td>@Salary.UserProfile.LastName   </td>
                                <td>@Salary.UserProfile.Email   </td>
                                <td>@Salary.UserProfile.GradeName   </td>

                                <td>@Salary.Month  </td>
                                <td>@Salary.Year </td>
                                <td>@Salary.UserProfile.BasicSalary   </td>
                                <td>@Salary.UserProfile.TotAllowance   </td>
                                <td>@Salary.UserProfile.TotDeduction   </td>
                                <td>@Salary.UserProfile.NetPay   </td>
                                <td>@Salary.CreatedBy  </td>
                                <td>@Salary.DateCreated    </td>




                                <td><a asp-action="Edit" asp-route-id="@Salary.Id" alt="Edit"><i class="ti-pencil" aria-hidden="true"></i></a> </td>
                                <td><a onclick="return confirm('Are you sure you want to delete this record');" asp-action="Delete" asp-route-id="@Salary.Id"><i class="ti-trash" aria-hidden="true"></i></a> </td>

                                <td>
                                    <a asp-controller="Salary" asp-action="YearlyReport" asp-route-id="@Salary.Id" class="btn float-right hidden-sm-down btn-success"><i class="mdi mdi-plus-circle"></i>Salary Report</a>
                                </td>
                                <td>
                                    <a asp-controller="Salary" asp-action="MonthlySalary" asp-route-id="@Salary.Id" class="btn float-right hidden-sm-down btn-success"><i class="mdi mdi-plus-circle"></i>Monthly Salary Report</a>
                                </td>

                            </tr>


                            }

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>

</div>

@*{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>
    *@

StaffPortal/Views/Salary/UserMonthlyReport.cshtml
@model IEnumerable<StaffPortal.Entities.Salary>
@{
    ViewBag.Title = "Year";
}
<!-- ============================================================== -->

<div class="row">
    <div class="col-sm-12">

        <div class="white-box">

            <div style="font-family:Arial">

                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>


                                <th>
                                    Email
                                </th>
                                <th>
                                    Month
                                </th>
                                <th>
                                    Year
                                </th>
                                <th>
                                    Basic Salary
                                </th>
                                <th>
                                    Total Allowance
                                </th>
                                <th>
                                    Total Deduction
                                </th>

                                <th>
                                    Net Pay
                                </th>


                            </tr>

                        </thead>
                        <tbody>

                            @foreach (var Salary in Model)
                            {
                            <tr>


                                <td>@Salary.UserProfile.Email   </td>
                                <td> @Salary.Month </td>
                                <td>@Salary.Year </td>
                                <td>@Salary.UserProfile.BasicSalary </td>
                                <td>@Salary.UserProfile.TotAllowance </td>
                                <td>@Salary.UserProfile.TotDeduction </td>
                                <td>@Salary.UserProfile.NetPay </td>



                                <td>

                                    <a href="http://localhost:17442/Salary/UserMonthlyDetails/@Salary.Id" target="_blank" class="btn float-right hidden-sm-down btn-success"><i class="mdi mdi-plus-circle"></i>Salary Details</a>
                                </td>
                            </tr>


                            }

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>

</div>

@*{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }

    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex - 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @prevDisabled">
        Previous
    </a>
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex + 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @nextDisabled">
        Next
    </a>
*@

StaffPortal/Views/Salary/UserYear.cshtml
   @model IEnumerable<StaffPortal.Entities.Salary>
@{
    ViewBag.Title = "Year";
}
<!-- ============================================================== -->

<div class="row">
    <div class="col-sm-12">

        <div class="white-box">

            @*<a asp-controller="Salary" asp-action="Create" class="btn float-right hidden-sm-down btn-success"><i class="mdi mdi-plus-circle"></i>New Salary</a>*@
            <div style="font-family:Arial">

                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>


                                <th>
                                    Email
                                </th>
                                <th>
                                    Grade Name
                                </th>
                                <th>
                                    Year
                                </th>
                                <th>
                                    Total Allowance
                                </th>



                                <th>
                                    Total Deduction
                                </th>

                                <th>
                                    Total NetPay
                                </th>


                            </tr>

                        </thead>
                        <tbody>

                            @foreach (var Salary in Model)
                            {
                            <tr>
                                
                                
                                <td>@Salary.UserProfile.Email   </td>
                                <td> @Salary.UserProfile.GradeName </td>

                                <td>@Salary.Year </td>

                                <td>@Salary.YearAllow  </td>
                                <td> @Salary.YearDeduction   </td>
                                <td> @Salary.YearPay   </td>




                                <td><a asp-action="Edit" asp-route-id="@Salary.Id" alt="Edit"><i class="ti-pencil" aria-hidden="true"></i></a> </td>
                                <td><a onclick="return confirm('Are you sure you want to delete all of the records  for   @Salary.UserProfile.FirstName  @Salary.UserProfile.LastName for the Year: @Salary.Year');" asp-action="DeleteYear" asp-route-id="@Salary.Id"><i class="ti-trash" aria-hidden="true"></i></a> </td>

                              
                                <td>
                                   
                                        <a href="http://localhost:49821/Salary/UserYearlyReport/@Salary.Id" target="_blank"  class="btn float-right hidden-sm-down btn-success"><i class="mdi mdi-plus-circle"></i>Salary Report</a>
                                </td>
                            </tr>


                            }

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>

</div>

@*{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>
    *@

StaffPortal/Views/Salary/Year.cshtml
   @model IEnumerable<StaffPortal.Entities.Salary>
@{
    ViewBag.Title = "Year";
}
<!-- ============================================================== -->

<div class="row bg-title">
    <div class="col-lg-12">
        <h4 class="page-title">Salary</h4>
        <ol class="breadcrumb">
            <li><a href="#">Dashboard</a></li>
            <li class="active">Salary</li>
        </ol>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-sm-12">

        <div class="white-box">

            <a asp-controller="Salary" asp-action="Create" class="btn float-right hidden-sm-down btn-success"><i class="mdi mdi-plus-circle"></i>New Salary</a>
            <div style="font-family:Arial">

                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>

                                <th>
                                    Firstname
                                </th>
                                <th>
                                    Lastname
                                </th>
                                <th>
                                    Email
                                </th>
                                <th>
                                    Grade Name
                                </th>
                                <th>
                                    Year
                                </th>
                                <th>
                                    Total Allowance
                                </th>



                                <th>
                                    Total Deduction
                                </th>

                                <th>
                                    Total NetPay
                                </th>


                            </tr>

                        </thead>
                        <tbody>

                            @foreach (var Salary in Model)
                            {
                            <tr>
                                
                                <td>@Salary.UserProfile.FirstName   </td>
                                <td>@Salary.UserProfile.LastName   </td>
                                <td>@Salary.UserProfile.Email   </td>
                                <td> @Salary.UserProfile.GradeName </td>

                                <td>@Salary.Year </td>

                                <td>@Salary.YearAllow  </td>
                                <td> @Salary.YearDeduction   </td>
                                <td> @Salary.YearPay   </td>




                                <td><a asp-action="Edit" asp-route-id="@Salary.Id" alt="Edit"><i class="ti-pencil" aria-hidden="true"></i></a> </td>
                                <td><a onclick="return confirm('Are you sure you want to delete this record');" asp-action="Delete" asp-route-id="@Salary.Id"><i class="ti-trash" aria-hidden="true"></i></a> </td>

                              
                                <td>
                                    <a asp-controller="Salary" asp-action="YearlyReport" asp-route-id="@Salary.Id" class="btn float-right hidden-sm-down btn-success"><i class="mdi mdi-plus-circle"></i>Salary Report</a>
                                </td>
                            </tr>


                            }

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>

</div>

@*{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>
    *@